doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/domain'
                prefix: 'App\Domain'
                alias: App
                type: xml
            NickServ:
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/nickserv'
                prefix: 'App\NickServ\Domain\Entity'
                alias: NickServ
                type: xml
            MemoServ:
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/memoserv'
                prefix: 'App\MemoServ\Domain\Entity'
                alias: MemoServ
                type: xml


doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
