framework:
    default_locale: '%env(SERVICES_DEFAULT_LANGUAGE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        paths:
            - '%kernel.project_dir%/translations'
